name: Feature Request
description: Suggest a new feature or enhancement for Wassette
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of what you want to happen
      placeholder: Describe the feature you'd like to see
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed? What problem does it solve?
      placeholder: |
        What problem does this solve?
        How would this improve Wassette?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
      placeholder: |
        Describe your proposed implementation or approach
        Include examples if applicable

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area of Wassette does this feature relate to?
      options:
        - Core Runtime
        - Component Loading
        - Permission System
        - MCP Protocol
        - CLI Tools
        - Documentation
        - Registry
        - Security
        - Testing
        - GitHub Actions Integration
        - Other (please specify in additional context)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe alternatives you've considered

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Provide examples of how this feature would be used
      placeholder: |
        ```bash
        # Example command or usage
        wassette ...
        ```
      render: shell

  - type: checkboxes
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this feature introduce any breaking changes?
      options:
        - label: This feature would require breaking changes
        - label: This feature maintains backward compatibility

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references
      placeholder: |
        Links to related issues, discussions, or external resources
        Screenshots or diagrams if applicable
